# Generated by Django 5.1.6 on 2025-02-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dangeroussubstance',
            old_name='name',
            new_name='name_ro',
        ),
        migrations.AddField(
            model_name='dangeroussubstance',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
